language: c++

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.5
    packages:
      - libtclap-dev
      - build-essential
      - gcc-4.9
      - g++-4.9
      - gcc-5
      - g++-5
      - gcc-6
      - g++-6
      - texlive
      - texlive-extra-utils

matrix:
  include:
    - env: TRAVIS_CC=gcc-4.9   TRAVIS_CXX=g++-4.9
    - env: TRAVIS_CC=gcc-5     TRAVIS_CXX=g++-5
    - env: TRAVIS_CC=gcc-6     TRAVIS_CXX=g++-6

before_install:
  - export PATH="${HOME}/dependencies/install/bin:$PATH"
  - export PKG_CONFIG_PATH="${HOME}/dependencies/install/lib/pkgconfig"
  - export CC=$TRAVIS_CC
  - export CXX=$TRAVIS_CXX
  - PCONFIGURE_VERSION=0.11.10
  - PSON_VERSION=0.0.3
  - export MAKEFLAGS="-j3"
  - export S="$(pwd)"
  - mkdir -p "${HOME}/dependencies"
  - cd "${HOME}/dependencies"
  - wget "https://github.com/palmer-dabbelt/pconfigure/archive/v${PCONFIGURE_VERSION}.tar.gz" -O "${PCONFIGURE_VERSION}.tar.gz"
  - tar -xvzpf "${PCONFIGURE_VERSION}.tar.gz"
  - cd "pconfigure-${PCONFIGURE_VERSION}"
  - ./bootstrap.sh --prefix "${HOME}/dependencies/install"
  - make install
  - cd "${HOME}/dependencies"
  - wget "https://github.com/palmer-dabbelt/pson/archive/v${PSON_VERSION}.tar.gz" -O "${PSON_VERSION}.tar.gz"
  - tar -xvzpf "${PSON_VERSION}.tar.gz"
  - cd "pson-${PSON_VERSION}"
  - pconfigure --verbose "PREFIX = ${HOME}/dependencies/install"
  - make
  - make install
  - cd "${S}"

script:
  - pconfigure --verbose
  - make
  - PATH="$(pwd)/bin:$PATH" make check
  - ptest --verbose
